language: objective-c
osx_image: xcode7.2
rvm:
  - 2.2.3
before_install:
  - gem install cocoapods --pre
  - pod repo update --silent
script:
 - xctool -scheme racquet-ios -sdk iphonesimulator -workspace racquet-ios.xcworkspace ONLY_ACTIVE_ARCH=NO
 - xctool test -scheme racquet-ios -sdk iphonesimulator -workspace racquet-ios.xcworkspace ONLY_ACTIVE_ARCH=NO
