language: objective-c
osx_image: xcode7.2
rvm:
  - 2.2.3
before_install:
  - gem install cocoapods --pre
  - pod repo update --silent
  - gem install xcpretty
script:
 - set -o pipefail && xcodebuild -scheme racquet-ios -sdk iphonesimulator -workspace racquet-ios.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' ONLY_ACTIVE_ARCH=NO clean test | xcpretty -tc
